### ISSUE TITLE
x509-certificate-exporter:3.2.0 contains CVE-2022-2097 (alpine 3.14.6)

### ISSUE THREAD

**Issue by c0nsaw** [enix/x509-certificate-exporter#40]
Was unable pull the v3.20 image into my company's artifactory, current image contains CVE-2022-2097 (alpine 3.14.6)
libcrypto1.1
libssl1.1

**Comment by npdgm** [comment]
Hi @c0nsaw

Sorry about the delay, we made the change quickly after you opened the issue but could not release for a while because of CI issues. Gitlab had troubles with repository mirroring and then there was a caching issue on our runners.

The fix is available from version 3.2.1

I know there are other security alerts raised by Trivy related to Golang. We're working on that as some more testing is required.

Thanks for taking the time to report this issue.
Cheers
