### ISSUE TITLE
Feature: Support list of URLs to monitor

### ISSUE THREAD

**Issue by braunsonm** [enix/x509-certificate-exporter#68]
Hello, this tool looks great!

We would love to use it in addition to the existing features, to monitor application certificates which might not be running on Kubernetes. Similar to the tool [doomsday](https://github.com/doomsday-project/doomsday), what I propose is a configuration option like so:

```yaml
monitorUrls:
- https://example.com
- https://my-app.com
```

This would check the certificate being served and export metrics about it.

Thanks!

**Comment by npdgm** [comment]
Hello!

Looking back at the motivations for starting this project, was a dissatisfaction with existing exporters. Not for a lack of feature which could have been fixed, it was more about having the right scope and being light. Doing just one thing well.

The goal has been to create a unique metrics interface for monitoring all certificates stored in a Kubernetes clusters, both files and API objects. This is to ensure all **configurations** are acceptable with healthy certificates, by looking at the source where they are stored and to be maintained.
As such it is much expected to want even more sources of certificates to be incorporated, and get a streamlined experience with metrics, alerts, and even dashboards common for a whole infrastructure.

Probing HTTPS servers would challenge our design principles. This is known as blackbox testing and it's a whole different thing.
There would be more settings to add and situations to take care of. Such as connection parameters, network timeouts, hybrid certificates (RSA + ECC), maybe issues with mTLS, etc. And it could easily turn into a rabbit hole with requests to support additional protocols for email servers, databases, or message brokers. Some protocols don't always use plain TLS sessions and require specific code for StartTLS to begin.

I'm not saying we can't implement your request solely because the rationale is incompatible with a vision. Truth is there are very good exporters designed specifically for probing network servers already. Dedicated to the task and continuously improved and tested as protocols evolve. HTTP/3, ESNI, etc... we really don't want to get into issues with those should there be anything lacking in Go libraries. We can't pretend to doing that well and will stick to the scope of configuration sources of truth.

So to wrap it all up, please have a look at [blackbox_exporter](https://github.com/prometheus/blackbox_exporter) which should answer your use case. It has metrics about certificates, for the tcp or http target I don't remember. As I said about the genesis of our project, we're very well aware it's inconvenient to merge metrics of several exporters to alert on similar.

Cheers

**Comment by braunsonm** [comment]
Thanks @npdgm I wasn't aware of the blackbox_exporter, that will suite our needs better.

**Comment by npdgm** [comment]
You're welcome. Look for metric `probe_ssl_earliest_cert_expiry`.
They also have interesting insights on how long each phase of establishing a resquest take: DNS resolution, connection, TLS handshake, etc.

**Comment by alwaysastudent** [comment]
> Hello!
> 
> Looking back at the motivations for starting this project, was a dissatisfaction with existing exporters. Not for a lack of feature which could have been fixed, it was more about having the right scope and being light. Doing just one thing well.
> 
> The goal has been to create a unique metrics interface for monitoring all certificates stored in a Kubernetes clusters, both files and API objects. This is to ensure all **configurations** are acceptable with healthy certificates, by looking at the source where they are stored and to be maintained. As such it is much expected to want even more sources of certificates to be incorporated, and get a streamlined experience with metrics, alerts, and even dashboards common for a whole infrastructure.
> 
> Probing HTTPS servers would challenge our design principles. This is known as blackbox testing and it's a whole different thing. There would be more settings to add and situations to take care of. Such as connection parameters, network timeouts, hybrid certificates (RSA + ECC), maybe issues with mTLS, etc. And it could easily turn into a rabbit hole with requests to support additional protocols for email servers, databases, or message brokers. Some protocols don't always use plain TLS sessions and require specific code for StartTLS to begin.
> 
> I'm not saying we can't implement your request solely because the rationale is incompatible with a vision. Truth is there are very good exporters designed specifically for probing network servers already. Dedicated to the task and continuously improved and tested as protocols evolve. HTTP/3, ESNI, etc... we really don't want to get into issues with those should there be anything lacking in Go libraries. We can't pretend to doing that well and will stick to the scope of configuration sources of truth.
> 
> So to wrap it all up, please have a look at [blackbox_exporter](https://github.com/prometheus/blackbox_exporter) which should answer your use case. It has metrics about certificates, for the tcp or http target I don't remember. As I said about the genesis of our project, we're very well aware it's inconvenient to merge metrics of several exporters to alert on similar issues.
> 
> Cheers

/reopen

This would be a great addition to this exporter, why is it so hard to do  some check like this? And be with it. Never asking to overcomplicate it. Keep it simple and just give us a way to pass in custom trust bundles for the URLs we want to track the expiry. 



`
echo | openssl s_client -connect www.google.com:443 2>/dev/null | openssl x509 -noout -dates -subject

echo | openssl s_client -connect  some.internal.domain:443 2>/dev/null | openssl x509 -noout -dates -subject -CAfile trust-ca.pem

`
