### ISSUE TITLE
Handle Password protected certificates

### ISSUE THREAD

**Issue by dadicool** [enix/x509-certificate-exporter#74]
Hi,

we have certificates which are password protected and we would like to monitor them.
Looking at the docs, I don't see any reference to it and the implementation doesn't handle it here : https://github.com/enix/x509-certificate-exporter/blob/ca89d322e37e3db87591baa812680b2a4ad0f6f5/internal/certificate.go#L275

We foresee an implementation as follows :
- the certificate object in k8s has a label annotation that indicates the secret that holds the password to decode the certificate
- the exporter is capable of reading the certificate and then discover that there is an associated password and reads it to decode the certificate
- after this decode, the rest of the processing pipeline goes as usual

Does this make sense?

Dali

**Comment by npdgm** [comment]
Hi @dadicool,

Could you please confirm you are using encrypted PEM blocks as per RFC 1423?

I had no idea they existed. It seems to be a vulnerable and defunct specification from 1993, using DES and MD2/MD5 with no update to modern cryptographic standards. There are mentions to vulnerabilities dating back from at least 2001.
Support was added to Go but is now flagged as deprecated, so it would not be wise for us to start using such facility.

Otherwise I can't see how you could have a passphrase for a **certificate**. Or perhaps it's actually about PKCS (PFX) bundles?

Cheers
